In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("test.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

In [6]:
print(df.columns)

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [8]:
for col in df.columns:
    if df[col].dtype=='object':
        df[col].fillna(df[col].mode()[0],inplace=True)
    else:
        df[col].fillna(df[col].mean(),inplace=True)

In [9]:
df.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [10]:
df.columns.tolist()

['PassengerId',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [11]:
df['Name'].value_counts()

Hipkins, Mr. William Edward                                       1
Chaudanson, Miss. Victorine                                       1
Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)    1
Lahtinen, Rev. William                                            1
Astor, Col. John Jacob                                            1
                                                                 ..
Aks, Master. Philip Frank                                         1
Pearce, Mr. Ernest                                                1
Lennon, Miss. Mary                                                1
Colbert, Mr. Patrick                                              1
Case, Mr. Howard Brown                                            1
Name: Name, Length: 418, dtype: int64

In [12]:
df.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,B57 B59 B63 B66,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,B57 B59 B63 B66,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,B57 B59 B63 B66,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,B57 B59 B63 B66,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,B57 B59 B63 B66,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,B57 B59 B63 B66,S
6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,B57 B59 B63 B66,Q
7,899,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,B57 B59 B63 B66,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,B57 B59 B63 B66,C
9,901,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,B57 B59 B63 B66,S

In [13]:
df=pd.get_dummies(df,columns=['Name'],dtype=int)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Columns: 428 entries, PassengerId to Name_van Billiard, Master. Walter John
dtypes: float64(2), int64(422), object(4)
memory usage: 1.4+ MB

In [15]:
df['Ticket'].value_counts()

PC 17608              5
CA. 2343              4
113503                4
SOTON/O.Q. 3101315    3
PC 17483              3
                     ..
237789                1
368783                1
2543                  1
365235                1
2658                  1
Name: Ticket, Length: 363, dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Columns: 428 entries, PassengerId to Name_van Billiard, Master. Walter John
dtypes: float64(2), int64(422), object(4)
memory usage: 1.4+ MB

In [17]:
df = pd.read_csv("test.csv")

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

In [19]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [20]:
df['Name']=encoder.fit_transform(df['Name'])

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    int64
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 36.0+ KB

In [22]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,206,male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,403,female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,269,male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,408,male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,178,female,22.0,1,1,3101298,12.2875,NaN,S

In [23]:
df['Name'].value_counts().sum()

418

Frequence Encoding

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    int64
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 36.0+ KB

In [25]:
df['Parch'].value_counts()

0    324
1     52
2     33
3      3
4      2
9      2
5      1
6      1
Name: Parch, dtype: int64

In [26]:
frequency_encoding=df['Cabin'].value_counts().to_dict()

In [27]:
frequency_encoding

{'B57 B59 B63 B66': 3,
 'C55 C57': 2,
 'C101': 2,
 'C78': 2,
 'B45': 2,
 'C89': 2,
 'C80': 2,
 'E34': 2,
 'A34': 2,
 'C23 C25 C27': 2,
 'C31': 2,
 'F4': 2,
 'C6': 2,
 'C116': 2,
 'D10 D12': 1,
 'E45': 1,
 'D15': 1,
 'D': 1,
 'E52': 1,
 'A29': 1,
 'B78': 1,
 'B24': 1,
 'D19': 1,
 'B52 B54 B56': 1,
 'E60': 1,
 'B11': 1,
 'C105': 1,
 'B26': 1,
 'C130': 1,
 'C46': 1,
 'C54': 1,
 'C22 C26': 1,
 'C62 C64': 1,
 'C28': 1,
 'D40': 1,
 'D38': 1,
 'F2': 1,
 'F33': 1,
 'B58 B60': 1,
 'F G63': 1,
 'E39 E41': 1,
 'G6': 1,
 'C32': 1,
 'C51': 1,
 'C86': 1,
 'A11': 1,
 'C106': 1,
 'D30': 1,
 'C132': 1,
 'B71': 1,
 'D37': 1,
 'F': 1,
 'F E57': 1,
 'A18': 1,
 'F E46': 1,
 'B10': 1,
 'C7': 1,
 'E46': 1,
 'E31': 1,
 'C53': 1,
 'B51 B53 B55': 1,
 'C85': 1,
 'D34': 1,
 'D28': 1,
 'B41': 1,
 'A9': 1,
 'C39': 1,
 'B36': 1,
 'A21': 1,
 'C97': 1,
 'D43': 1,
 'D21': 1,
 'B61': 1,
 'D22': 1,
 'B69': 1,
 'E50': 1}

In [28]:
frequency_encoding=df['Cabin'].value_counts().to_dict()
df['Cabin_encoded']=df['Cabin'].map(frequency_encoding)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PassengerId    418 non-null    int64
 1   Pclass         418 non-null    int64
 2   Name           418 non-null    int64
 3   Sex            418 non-null    object
 4   Age            332 non-null    float64
 5   SibSp          418 non-null    int64
 6   Parch          418 non-null    int64
 7   Ticket         418 non-null    object
 8   Fare           417 non-null    float64
 9   Cabin          91 non-null     object
 10  Embarked       418 non-null    object
 11  Cabin_encoded  91 non-null     float64
dtypes: float64(3), int64(5), object(4)
memory usage: 39.3+ KB

In [30]:
df.drop(('Cabin'),axis=1,inplace=True)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PassengerId    418 non-null    int64
 1   Pclass         418 non-null    int64
 2   Name           418 non-null    int64
 3   Sex            418 non-null    object
 4   Age            332 non-null    float64
 5   SibSp          418 non-null    int64
 6   Parch          418 non-null    int64
 7   Ticket         418 non-null    object
 8   Fare           417 non-null    float64
 9   Embarked       418 non-null    object
 10  Cabin_encoded  91 non-null     float64
dtypes: float64(3), int64(5), object(3)
memory usage: 36.0+ KB

#Target Encoding

In [32]:
df['Fare'].value_counts()

7.7500      21
26.0000     19
8.0500      17
13.0000     17
7.8958      11
            ..
31.6833      1
16.0000      1
53.1000      1
146.5208     1
20.2500      1
Name: Fare, Length: 169, dtype: int64

In [36]:
import category_encoders as ce # type: ignore

ModuleNotFoundError: No module named 'category_encoders'