In [30]:
import pandas as pd

In [31]:
df=pd.read_csv('Supplement_Sales_Weekly_Expanded.csv')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            4384 non-null   object
 1   Product Name    4384 non-null   object
 2   Category        4384 non-null   object
 3   Units Sold      4384 non-null   int64
 4   Price           4384 non-null   float64
 5   Revenue         4384 non-null   float64
 6   Discount        4384 non-null   float64
 7   Units Returned  4384 non-null   int64
 8   Location        4384 non-null   object
 9   Platform        4384 non-null   object
dtypes: float64(3), int64(2), object(5)
memory usage: 342.6+ KB

In [33]:
for col in df.columns:
    if df[col].isnull().sum()>0:
        if df[col].dtype=='object':
            df[col].fillna(df[col].mode()[0],inplace=True)
        else:
            df[col].fillna(df[col].mean(),inplace=True)

In [34]:
df.isnull().sum()

Date              0
Product Name      0
Category          0
Units Sold        0
Price             0
Revenue           0
Discount          0
Units Returned    0
Location          0
Platform          0
dtype: int64

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            4384 non-null   object
 1   Product Name    4384 non-null   object
 2   Category        4384 non-null   object
 3   Units Sold      4384 non-null   int64
 4   Price           4384 non-null   float64
 5   Revenue         4384 non-null   float64
 6   Discount        4384 non-null   float64
 7   Units Returned  4384 non-null   int64
 8   Location        4384 non-null   object
 9   Platform        4384 non-null   object
dtypes: float64(3), int64(2), object(5)
memory usage: 342.6+ KB

#one-hot encoding

In [36]:
df['Revenue'].value_counts()

3638.60    2
3848.82    2
7256.48    2
5705.70    2
2207.52    2
          ..
1645.52    1
7161.28    1
8830.53    1
7823.76    1
2746.80    1
Name: Revenue, Length: 4326, dtype: int64

In [37]:
df.head(10)

,Date,Product Name,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform
0,2020-01-06,Whey Protein,Protein,143,31.98,4573.14,0.03,2,Canada,Walmart
1,2020-01-06,Vitamin C,Vitamin,139,42.51,5908.89,0.04,0,UK,Amazon
2,2020-01-06,Fish Oil,Omega,161,12.91,2078.51,0.25,0,Canada,Amazon
3,2020-01-06,Multivitamin,Vitamin,140,16.07,2249.80,0.08,0,Canada,Walmart
4,2020-01-06,Pre-Workout,Performance,157,35.47,5568.79,0.25,3,Canada,iHerb
5,2020-01-06,BCAA,Amino Acid,154,41.19,6343.26,0.13,1,UK,Walmart
6,2020-01-06,Creatine,Performance,134,32.49,4353.66,0.05,1,UK,Walmart
7,2020-01-06,Zinc,Mineral,147,46.68,6861.96,0.19,0,Canada,Amazon
8,2020-01-06,Collagen Peptides,Protein,147,10.96,1611.12,0.06,2,USA,Amazon
9,2020-01-06,Magnesium,Mineral,134,20.76,2781.84,0.00,0,Canada,Amazon

In [38]:
df=pd.get_dummies(df,columns=['Product Name'],dtype=int)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Date                             4384 non-null   object
 1   Category                         4384 non-null   object
 2   Units Sold                       4384 non-null   int64
 3   Price                            4384 non-null   float64
 4   Revenue                          4384 non-null   float64
 5   Discount                         4384 non-null   float64
 6   Units Returned                   4384 non-null   int64
 7   Location                         4384 non-null   object
 8   Platform                         4384 non-null   object
 9   Product Name_Ashwagandha         4384 non-null   int64
 10  Product Name_BCAA                4384 non-null   int64
 11  Product Name_Biotin              4384 non-null   int64
 12  Product Name_Collagen Peptides   4384 non-null   int64
 13  Product Name_Creatine            4384 non-null   int64
 14  Product Name_Electrolyte Powder  4384 non-null   int64
 15  Product Name_Fish Oil            4384 non-null   int64
 16  Product Name_Green Tea Extract   4384 non-null   int64
 17  Product Name_Iron Supplement     4384 non-null   int64
 18  Product Name_Magnesium           4384 non-null   int64
 19  Product Name_Melatonin           4384 non-null   int64
 20  Product Name_Multivitamin        4384 non-null   int64
 21  Product Name_Pre-Workout         4384 non-null   int64
 22  Product Name_Vitamin C           4384 non-null   int64
 23  Product Name_Whey Protein        4384 non-null   int64
 24  Product Name_Zinc                4384 non-null   int64
dtypes: float64(3), int64(18), object(4)
memory usage: 856.4+ KB

In [40]:
df.head()

,Date,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform,Product Name_Ashwagandha,...,Product Name_Fish Oil,Product Name_Green Tea Extract,Product Name_Iron Supplement,Product Name_Magnesium,Product Name_Melatonin,Product Name_Multivitamin,Product Name_Pre-Workout,Product Name_Vitamin C,Product Name_Whey Protein,Product Name_Zinc
0,2020-01-06,Protein,143,31.98,4573.14,0.03,2,Canada,Walmart,0,...,0,0,0,0,0,0,0,0,1,0
1,2020-01-06,Vitamin,139,42.51,5908.89,0.04,0,UK,Amazon,0,...,0,0,0,0,0,0,0,1,0,0
2,2020-01-06,Omega,161,12.91,2078.51,0.25,0,Canada,Amazon,0,...,1,0,0,0,0,0,0,0,0,0
3,2020-01-06,Vitamin,140,16.07,2249.80,0.08,0,Canada,Walmart,0,...,0,0,0,0,0,1,0,0,0,0
4,2020-01-06,Performance,157,35.47,5568.79,0.25,3,Canada,iHerb,0,...,0,0,0,0,0,0,1,0,0,0

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Date                             4384 non-null   object
 1   Category                         4384 non-null   object
 2   Units Sold                       4384 non-null   int64
 3   Price                            4384 non-null   float64
 4   Revenue                          4384 non-null   float64
 5   Discount                         4384 non-null   float64
 6   Units Returned                   4384 non-null   int64
 7   Location                         4384 non-null   object
 8   Platform                         4384 non-null   object
 9   Product Name_Ashwagandha         4384 non-null   int64
 10  Product Name_BCAA                4384 non-null   int64
 11  Product Name_Biotin              4384 non-null   int64
 12  Product Name_Collagen Peptides   4384 non-null   int64
 13  Product Name_Creatine            4384 non-null   int64
 14  Product Name_Electrolyte Powder  4384 non-null   int64
 15  Product Name_Fish Oil            4384 non-null   int64
 16  Product Name_Green Tea Extract   4384 non-null   int64
 17  Product Name_Iron Supplement     4384 non-null   int64
 18  Product Name_Magnesium           4384 non-null   int64
 19  Product Name_Melatonin           4384 non-null   int64
 20  Product Name_Multivitamin        4384 non-null   int64
 21  Product Name_Pre-Workout         4384 non-null   int64
 22  Product Name_Vitamin C           4384 non-null   int64
 23  Product Name_Whey Protein        4384 non-null   int64
 24  Product Name_Zinc                4384 non-null   int64
dtypes: float64(3), int64(18), object(4)
memory usage: 856.4+ KB

In [42]:
df.head()

,Date,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform,Product Name_Ashwagandha,...,Product Name_Fish Oil,Product Name_Green Tea Extract,Product Name_Iron Supplement,Product Name_Magnesium,Product Name_Melatonin,Product Name_Multivitamin,Product Name_Pre-Workout,Product Name_Vitamin C,Product Name_Whey Protein,Product Name_Zinc
0,2020-01-06,Protein,143,31.98,4573.14,0.03,2,Canada,Walmart,0,...,0,0,0,0,0,0,0,0,1,0
1,2020-01-06,Vitamin,139,42.51,5908.89,0.04,0,UK,Amazon,0,...,0,0,0,0,0,0,0,1,0,0
2,2020-01-06,Omega,161,12.91,2078.51,0.25,0,Canada,Amazon,0,...,1,0,0,0,0,0,0,0,0,0
3,2020-01-06,Vitamin,140,16.07,2249.80,0.08,0,Canada,Walmart,0,...,0,0,0,0,0,1,0,0,0,0
4,2020-01-06,Performance,157,35.47,5568.79,0.25,3,Canada,iHerb,0,...,0,0,0,0,0,0,1,0,0,0

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Date                             4384 non-null   object
 1   Category                         4384 non-null   object
 2   Units Sold                       4384 non-null   int64
 3   Price                            4384 non-null   float64
 4   Revenue                          4384 non-null   float64
 5   Discount                         4384 non-null   float64
 6   Units Returned                   4384 non-null   int64
 7   Location                         4384 non-null   object
 8   Platform                         4384 non-null   object
 9   Product Name_Ashwagandha         4384 non-null   int64
 10  Product Name_BCAA                4384 non-null   int64
 11  Product Name_Biotin              4384 non-null   int64
 12  Product Name_Collagen Peptides   4384 non-null   int64
 13  Product Name_Creatine            4384 non-null   int64
 14  Product Name_Electrolyte Powder  4384 non-null   int64
 15  Product Name_Fish Oil            4384 non-null   int64
 16  Product Name_Green Tea Extract   4384 non-null   int64
 17  Product Name_Iron Supplement     4384 non-null   int64
 18  Product Name_Magnesium           4384 non-null   int64
 19  Product Name_Melatonin           4384 non-null   int64
 20  Product Name_Multivitamin        4384 non-null   int64
 21  Product Name_Pre-Workout         4384 non-null   int64
 22  Product Name_Vitamin C           4384 non-null   int64
 23  Product Name_Whey Protein        4384 non-null   int64
 24  Product Name_Zinc                4384 non-null   int64
dtypes: float64(3), int64(18), object(4)
memory usage: 856.4+ KB

In [44]:
df['Price'].value_counts()

31.37    7
33.39    6
44.34    6
27.10    5
32.01    5
        ..
18.05    1
25.54    1
34.24    1
41.64    1
16.74    1
Name: Price, Length: 2919, dtype: int64

Label Encoding

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Date                             4384 non-null   object
 1   Category                         4384 non-null   object
 2   Units Sold                       4384 non-null   int64
 3   Price                            4384 non-null   float64
 4   Revenue                          4384 non-null   float64
 5   Discount                         4384 non-null   float64
 6   Units Returned                   4384 non-null   int64
 7   Location                         4384 non-null   object
 8   Platform                         4384 non-null   object
 9   Product Name_Ashwagandha         4384 non-null   int64
 10  Product Name_BCAA                4384 non-null   int64
 11  Product Name_Biotin              4384 non-null   int64
 12  Product Name_Collagen Peptides   4384 non-null   int64
 13  Product Name_Creatine            4384 non-null   int64
 14  Product Name_Electrolyte Powder  4384 non-null   int64
 15  Product Name_Fish Oil            4384 non-null   int64
 16  Product Name_Green Tea Extract   4384 non-null   int64
 17  Product Name_Iron Supplement     4384 non-null   int64
 18  Product Name_Magnesium           4384 non-null   int64
 19  Product Name_Melatonin           4384 non-null   int64
 20  Product Name_Multivitamin        4384 non-null   int64
 21  Product Name_Pre-Workout         4384 non-null   int64
 22  Product Name_Vitamin C           4384 non-null   int64
 23  Product Name_Whey Protein        4384 non-null   int64
 24  Product Name_Zinc                4384 non-null   int64
dtypes: float64(3), int64(18), object(4)
memory usage: 856.4+ KB

In [46]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [47]:
df['Location']=encoder.fit_transform(df['Location'])

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Date                             4384 non-null   object
 1   Category                         4384 non-null   object
 2   Units Sold                       4384 non-null   int64
 3   Price                            4384 non-null   float64
 4   Revenue                          4384 non-null   float64
 5   Discount                         4384 non-null   float64
 6   Units Returned                   4384 non-null   int64
 7   Location                         4384 non-null   int64
 8   Platform                         4384 non-null   object
 9   Product Name_Ashwagandha         4384 non-null   int64
 10  Product Name_BCAA                4384 non-null   int64
 11  Product Name_Biotin              4384 non-null   int64
 12  Product Name_Collagen Peptides   4384 non-null   int64
 13  Product Name_Creatine            4384 non-null   int64
 14  Product Name_Electrolyte Powder  4384 non-null   int64
 15  Product Name_Fish Oil            4384 non-null   int64
 16  Product Name_Green Tea Extract   4384 non-null   int64
 17  Product Name_Iron Supplement     4384 non-null   int64
 18  Product Name_Magnesium           4384 non-null   int64
 19  Product Name_Melatonin           4384 non-null   int64
 20  Product Name_Multivitamin        4384 non-null   int64
 21  Product Name_Pre-Workout         4384 non-null   int64
 22  Product Name_Vitamin C           4384 non-null   int64
 23  Product Name_Whey Protein        4384 non-null   int64
 24  Product Name_Zinc                4384 non-null   int64
dtypes: float64(3), int64(19), object(3)
memory usage: 856.4+ KB

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Date                             4384 non-null   object
 1   Category                         4384 non-null   object
 2   Units Sold                       4384 non-null   int64
 3   Price                            4384 non-null   float64
 4   Revenue                          4384 non-null   float64
 5   Discount                         4384 non-null   float64
 6   Units Returned                   4384 non-null   int64
 7   Location                         4384 non-null   int64
 8   Platform                         4384 non-null   object
 9   Product Name_Ashwagandha         4384 non-null   int64
 10  Product Name_BCAA                4384 non-null   int64
 11  Product Name_Biotin              4384 non-null   int64
 12  Product Name_Collagen Peptides   4384 non-null   int64
 13  Product Name_Creatine            4384 non-null   int64
 14  Product Name_Electrolyte Powder  4384 non-null   int64
 15  Product Name_Fish Oil            4384 non-null   int64
 16  Product Name_Green Tea Extract   4384 non-null   int64
 17  Product Name_Iron Supplement     4384 non-null   int64
 18  Product Name_Magnesium           4384 non-null   int64
 19  Product Name_Melatonin           4384 non-null   int64
 20  Product Name_Multivitamin        4384 non-null   int64
 21  Product Name_Pre-Workout         4384 non-null   int64
 22  Product Name_Vitamin C           4384 non-null   int64
 23  Product Name_Whey Protein        4384 non-null   int64
 24  Product Name_Zinc                4384 non-null   int64
dtypes: float64(3), int64(19), object(3)
memory usage: 856.4+ KB

In [50]:
df.head()

,Date,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform,Product Name_Ashwagandha,...,Product Name_Fish Oil,Product Name_Green Tea Extract,Product Name_Iron Supplement,Product Name_Magnesium,Product Name_Melatonin,Product Name_Multivitamin,Product Name_Pre-Workout,Product Name_Vitamin C,Product Name_Whey Protein,Product Name_Zinc
0,2020-01-06,Protein,143,31.98,4573.14,0.03,2,0,Walmart,0,...,0,0,0,0,0,0,0,0,1,0
1,2020-01-06,Vitamin,139,42.51,5908.89,0.04,0,1,Amazon,0,...,0,0,0,0,0,0,0,1,0,0
2,2020-01-06,Omega,161,12.91,2078.51,0.25,0,0,Amazon,0,...,1,0,0,0,0,0,0,0,0,0
3,2020-01-06,Vitamin,140,16.07,2249.80,0.08,0,0,Walmart,0,...,0,0,0,0,0,1,0,0,0,0
4,2020-01-06,Performance,157,35.47,5568.79,0.25,3,0,iHerb,0,...,0,0,0,0,0,0,1,0,0,0

In [51]:
df['Location'].value_counts().sum()

4384

FREQUENCE ENCODING

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Date                             4384 non-null   object
 1   Category                         4384 non-null   object
 2   Units Sold                       4384 non-null   int64
 3   Price                            4384 non-null   float64
 4   Revenue                          4384 non-null   float64
 5   Discount                         4384 non-null   float64
 6   Units Returned                   4384 non-null   int64
 7   Location                         4384 non-null   int64
 8   Platform                         4384 non-null   object
 9   Product Name_Ashwagandha         4384 non-null   int64
 10  Product Name_BCAA                4384 non-null   int64
 11  Product Name_Biotin              4384 non-null   int64
 12  Product Name_Collagen Peptides   4384 non-null   int64
 13  Product Name_Creatine            4384 non-null   int64
 14  Product Name_Electrolyte Powder  4384 non-null   int64
 15  Product Name_Fish Oil            4384 non-null   int64
 16  Product Name_Green Tea Extract   4384 non-null   int64
 17  Product Name_Iron Supplement     4384 non-null   int64
 18  Product Name_Magnesium           4384 non-null   int64
 19  Product Name_Melatonin           4384 non-null   int64
 20  Product Name_Multivitamin        4384 non-null   int64
 21  Product Name_Pre-Workout         4384 non-null   int64
 22  Product Name_Vitamin C           4384 non-null   int64
 23  Product Name_Whey Protein        4384 non-null   int64
 24  Product Name_Zinc                4384 non-null   int64
dtypes: float64(3), int64(19), object(3)
memory usage: 856.4+ KB

In [53]:
df['Category'].value_counts()

Mineral        822
Vitamin        822
Performance    548
Protein        548
Omega          274
Herbal         274
Amino Acid     274
Fat Burner     274
Sleep Aid      274
Hydration      274
Name: Category, dtype: int64

In [55]:
frequency_encoding=df['Category'].value_counts().to_dict()

In [56]:
frequency_encoding

{'Mineral': 822,
 'Vitamin': 822,
 'Performance': 548,
 'Protein': 548,
 'Omega': 274,
 'Herbal': 274,
 'Amino Acid': 274,
 'Fat Burner': 274,
 'Sleep Aid': 274,
 'Hydration': 274}

In [58]:
frequency_encoding=df['Category'].value_counts().to_dict()
df['Category_encoded']=df['Category'].map(frequency_encoding)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Date                             4384 non-null   object
 1   Category                         4384 non-null   object
 2   Units Sold                       4384 non-null   int64
 3   Price                            4384 non-null   float64
 4   Revenue                          4384 non-null   float64
 5   Discount                         4384 non-null   float64
 6   Units Returned                   4384 non-null   int64
 7   Location                         4384 non-null   int64
 8   Platform                         4384 non-null   object
 9   Product Name_Ashwagandha         4384 non-null   int64
 10  Product Name_BCAA                4384 non-null   int64
 11  Product Name_Biotin              4384 non-null   int64
 12  Product Name_Collagen Peptides   4384 non-null   int64
 13  Product Name_Creatine            4384 non-null   int64
 14  Product Name_Electrolyte Powder  4384 non-null   int64
 15  Product Name_Fish Oil            4384 non-null   int64
 16  Product Name_Green Tea Extract   4384 non-null   int64
 17  Product Name_Iron Supplement     4384 non-null   int64
 18  Product Name_Magnesium           4384 non-null   int64
 19  Product Name_Melatonin           4384 non-null   int64
 20  Product Name_Multivitamin        4384 non-null   int64
 21  Product Name_Pre-Workout         4384 non-null   int64
 22  Product Name_Vitamin C           4384 non-null   int64
 23  Product Name_Whey Protein        4384 non-null   int64
 24  Product Name_Zinc                4384 non-null   int64
 25  Category_encoded                 4384 non-null   int64
dtypes: float64(3), int64(20), object(3)
memory usage: 890.6+ KB

In [60]:
df.drop(('Category'),axis=1,inplace=True)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Date                             4384 non-null   object
 1   Units Sold                       4384 non-null   int64
 2   Price                            4384 non-null   float64
 3   Revenue                          4384 non-null   float64
 4   Discount                         4384 non-null   float64
 5   Units Returned                   4384 non-null   int64
 6   Location                         4384 non-null   int64
 7   Platform                         4384 non-null   object
 8   Product Name_Ashwagandha         4384 non-null   int64
 9   Product Name_BCAA                4384 non-null   int64
 10  Product Name_Biotin              4384 non-null   int64
 11  Product Name_Collagen Peptides   4384 non-null   int64
 12  Product Name_Creatine            4384 non-null   int64
 13  Product Name_Electrolyte Powder  4384 non-null   int64
 14  Product Name_Fish Oil            4384 non-null   int64
 15  Product Name_Green Tea Extract   4384 non-null   int64
 16  Product Name_Iron Supplement     4384 non-null   int64
 17  Product Name_Magnesium           4384 non-null   int64
 18  Product Name_Melatonin           4384 non-null   int64
 19  Product Name_Multivitamin        4384 non-null   int64
 20  Product Name_Pre-Workout         4384 non-null   int64
 21  Product Name_Vitamin C           4384 non-null   int64
 22  Product Name_Whey Protein        4384 non-null   int64
 23  Product Name_Zinc                4384 non-null   int64
 24  Category_encoded                 4384 non-null   int64
dtypes: float64(3), int64(20), object(2)
memory usage: 856.4+ KB

TARGET ENCODING

In [83]:
df['Platform'].value_counts()

iHerb      1499
Amazon     1473
Walmart    1412
Name: Platform, dtype: int64

In [88]:
# Importing the library
import category_encoders as ce   # type: ignore # type: ignore!which python

ModuleNotFoundError: No module named 'category_encoders'

In [89]:
encoder=ce.TargetEncoder(cols=['Embarked'])
df['Embarked_encoded']=encoder.fit_transform(df['Embarked'],df['Survived'])

NameError: name 'ce' is not defined

ORDINAL ENCODING

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Date                             4384 non-null   object
 1   Units Sold                       4384 non-null   int64
 2   Price                            4384 non-null   float64
 3   Revenue                          4384 non-null   float64
 4   Discount                         4384 non-null   float64
 5   Units Returned                   4384 non-null   int64
 6   Location                         4384 non-null   int64
 7   Platform                         4384 non-null   object
 8   Product Name_Ashwagandha         4384 non-null   int64
 9   Product Name_BCAA                4384 non-null   int64
 10  Product Name_Biotin              4384 non-null   int64
 11  Product Name_Collagen Peptides   4384 non-null   int64
 12  Product Name_Creatine            4384 non-null   int64
 13  Product Name_Electrolyte Powder  4384 non-null   int64
 14  Product Name_Fish Oil            4384 non-null   int64
 15  Product Name_Green Tea Extract   4384 non-null   int64
 16  Product Name_Iron Supplement     4384 non-null   int64
 17  Product Name_Magnesium           4384 non-null   int64
 18  Product Name_Melatonin           4384 non-null   int64
 19  Product Name_Multivitamin        4384 non-null   int64
 20  Product Name_Pre-Workout         4384 non-null   int64
 21  Product Name_Vitamin C           4384 non-null   int64
 22  Product Name_Whey Protein        4384 non-null   int64
 23  Product Name_Zinc                4384 non-null   int64
 24  Category_encoded                 4384 non-null   int64
dtypes: float64(3), int64(20), object(2)
memory usage: 856.4+ KB

In [95]:
from sklearn.preprocessing import OrdinalEncoder

# Ensure the column name is correct
print(df.columns)  # Check the column names in your DataFrame

# Apply Ordinal Encoding to the 'Platform' column
encoder = OrdinalEncoder(categories=[['amazon', 'Ebay', 'Etsy', 'Walmart']])
df['Platform_encoded'] = encoder.fit_transform(df[['Platform']])

# Verify the result
print(df[['Platform', 'Platform_encoded']].head())

Index(['Date', 'Units Sold', 'Price', 'Revenue', 'Discount', 'Units Returned',
       'Location', 'Platform', 'Product Name_Ashwagandha', 'Product Name_BCAA',
       'Product Name_Biotin', 'Product Name_Collagen Peptides',
       'Product Name_Creatine', 'Product Name_Electrolyte Powder',
       'Product Name_Fish Oil', 'Product Name_Green Tea Extract',
       'Product Name_Iron Supplement', 'Product Name_Magnesium',
       'Product Name_Melatonin', 'Product Name_Multivitamin',
       'Product Name_Pre-Workout', 'Product Name_Vitamin C',
       'Product Name_Whey Protein', 'Product Name_Zinc', 'Category_encoded'],
      dtype='object')

ValueError: Found unknown categories ['Amazon', 'iHerb'] in column 0 during fit

In [96]:
print(df.columns)

Index(['Date', 'Units Sold', 'Price', 'Revenue', 'Discount', 'Units Returned',
       'Location', 'Platform', 'Product Name_Ashwagandha', 'Product Name_BCAA',
       'Product Name_Biotin', 'Product Name_Collagen Peptides',
       'Product Name_Creatine', 'Product Name_Electrolyte Powder',
       'Product Name_Fish Oil', 'Product Name_Green Tea Extract',
       'Product Name_Iron Supplement', 'Product Name_Magnesium',
       'Product Name_Melatonin', 'Product Name_Multivitamin',
       'Product Name_Pre-Workout', 'Product Name_Vitamin C',
       'Product Name_Whey Protein', 'Product Name_Zinc', 'Category_encoded'],
      dtype='object')

In [98]:
df['Platform']

0       Walmart
1        Amazon
2        Amazon
3       Walmart
4         iHerb
         ...
4379      iHerb
4380    Walmart
4381      iHerb
4382     Amazon
4383      iHerb
Name: Platform, Length: 4384, dtype: object

In [100]:
df.drop('Platform',axis=1, inplace=True)

In [97]:
print(df['Platform'].unique())

['Walmart' 'Amazon' 'iHerb']

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Date                             4384 non-null   object
 1   Units Sold                       4384 non-null   int64
 2   Price                            4384 non-null   float64
 3   Revenue                          4384 non-null   float64
 4   Discount                         4384 non-null   float64
 5   Units Returned                   4384 non-null   int64
 6   Location                         4384 non-null   int64
 7   Product Name_Ashwagandha         4384 non-null   int64
 8   Product Name_BCAA                4384 non-null   int64
 9   Product Name_Biotin              4384 non-null   int64
 10  Product Name_Collagen Peptides   4384 non-null   int64
 11  Product Name_Creatine            4384 non-null   int64
 12  Product Name_Electrolyte Powder  4384 non-null   int64
 13  Product Name_Fish Oil            4384 non-null   int64
 14  Product Name_Green Tea Extract   4384 non-null   int64
 15  Product Name_Iron Supplement     4384 non-null   int64
 16  Product Name_Magnesium           4384 non-null   int64
 17  Product Name_Melatonin           4384 non-null   int64
 18  Product Name_Multivitamin        4384 non-null   int64
 19  Product Name_Pre-Workout         4384 non-null   int64
 20  Product Name_Vitamin C           4384 non-null   int64
 21  Product Name_Whey Protein        4384 non-null   int64
 22  Product Name_Zinc                4384 non-null   int64
 23  Category_encoded                 4384 non-null   int64
dtypes: float64(3), int64(20), object(1)
memory usage: 822.1+ KB